Fenetre:
    container: container
    BoxLayout:
        id: container
        orientation:"vertical"
        Label:
            text:"Mon jeu"

        BoxLayout:
            orientation:"vertical"
            Button:
                text:"Jouer"
                on_press:app.jouer('menu.kv')
            Button:
                text:"Options"
                on_press:app.option('menu.kv')
            Button:
                text:"Quitter"
                on_press:app.quitter()